version: '3.5'
services:
  jekyll:
      image: jekyll/jekyll
      environment:
        - JEKYLL_ENV=development
      command: jekyll serve --livereload --watch --host 0.0.0.0
      ports:
          - 4000:4000
      volumes:
          - .:/srv/jekyll