version: '3.5'
services:
  jekyll:
      image: jekyll/jekyll
      environment:
        - JEKYLL_ENV=development
      command: jekyll serve --trace --force_polling --watch --incremental --livereload-port 50000 -p 4000
      ports:
          - 4000:4000
          - 50000:50000
      volumes:
          - .:/srv/jekyll